# Grafana Datasource Provisioning
# Automatically configures Prometheus as a datasource

apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1

  # PostgreSQL/TimescaleDB (Analytics Database)
  - name: Analytics DB
    type: postgres
    access: proxy
    url: ${SUPABASE_HOST}:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: ${SUPABASE_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1400
      timescaledb: true
    editable: true
    version: 1

